### PR TITLE
Failing tests for record

### PR DESCRIPTION
**Pull request by mishun**

### CODE REVIEW

**Comment by mvkara** [comment]
- The mutable case has been resolved.
- The struct record case may be unfeasible to solve while we rely on protobuf-net's RuntimeTypeModel checks. In particular it validates the type you want to register is a value type; if it is it throws an InvalidOperationException no matter what. See https://github.com/protobuf-net/protobuf-net/blob/main/src/protobuf-net/Meta/RuntimeTypeModel.cs#L1975 for the line of code causing the issue upstream.

**Comment by mishun** [comment]
I was able to make value records work by emitting surrogate reference types (https://github.com/mishun/protobuf-net-fsharp/tree/emit-surrogates), but it required heavy modifications and retargeting to netstandard2.1

BTW, what should
https://github.com/mvkara/protobuf-net-fsharp/blob/da72fed8939e0ae53b5985e1e4558ceb9886455c/src/ProtoBuf.FSharp/ProtobufUtils.fs#L275-L282
do if passed Option&lt;Something&gt; or something like that?

**Comment by mvkara** [comment]
I can take a look at your branch as time permits.

Q: Wouldn't the value of using the surrogate be low in this case? You are allocating a reference type, then a struct. You could easily manually do that in code. You aren't really getting the performance benefit of a struct in this case vs doing the same process yourself in code. One of the motivations I had in writing this library is I didn't want to copy classes into a nicer record or union at my system boundary every time and get the allocation and performance hits - I just want to allocate the F# object only. If I have to do it anyway not sure of the point especially if it is hidden in the library? Struct allocation would seem slower than reference allocation which isn't intuitive. Happy to support it anyway (vs failing) to give a better experience and support some edge case but at the very least it probably isn't recommended to use.

On your other question if the Option<Type> is passed as the runtimeType parameter you mean? Haven't really looked into that as a supported case tbh; protobuf at the root level usually expects you to send "something" otherwise what's the point? We could support it by making it a union as I have done for the options inlined. On a side point at the root level it is usually recommended (even in protobuf) documentation to have a envelope type for your messages - that way adding a field or more data isn't ever a breaking change (i.e. changing Option<Something> to a new message type if you ever want to add anything to that request/response would be a breaking change, an envelope makes it a backwards compatible one). So it wouldn't be a common case but I'm not opposed to supporting it.

**Comment by mishun** [comment]
Well, both value records and Option are not very useful at root level. Where they can be useful is if we want to serialize some complicated data structure which has nested value types and options (as fields or generic arguments), especially if that data structure is created by third party. Options are needed in particular when they're inside type serialization for which needs to be user-defined for some reason.

It's possible to do something crazy about allocation overhead, like object pools, but I tried to make value type surrogates and they appear to work.

**Comment by mvkara** [comment]
Ok you've given me more details:

- Option types definitely work at the root level and as nested fields. They are part of the F# languages and for nested fields they were supported from the onset. Adding this test case also works so they are supported at the root level, although I don't recommend the pattern. They are supported using Surrogates as you probably know. This case when added to the Record test cases works.

`testCase "Can serialise string option directly" <| fun () -> testRoundtrip (Some "TEST")`

- As mentioned previously not opposed to supporting value type surrogates. Ideally we should only generate the surrogate in the case of value type unless we can ascertain that the performance isn't harmed in the other cases (i.e. we currently tell Protobuf-net to generate the object directly for everything other than options). If performance isn't harmed then we could generate everything using them - as a side point (its been awhile) I can't remember if surrogates support subtypes. If they do they could be a cleaner (or more sure) way of generating union case schema's.

**Comment by mishun** [comment]
If I understand correctly, in case of your example no option surrogates are involved: testRoundtrip calls registerRecordIntoModel which in turn calls processFieldsAndCreateFieldSetters which just creates factory for Option<>. That causes problems if None is present, for example (explicitly unrolling testRoundtrip):
```F#
        testCase "Option" <| fun () ->
            let typeToTest = [| Some "string1" ; None ; Some "string2" |]
            let model =  RuntimeTypeModel.Create() |> Serialiser.registerRecordIntoModel<string option>
            model.CompileInPlace()
            use ms = new MemoryStream()
            Serialiser.serialise model ms typeToTest
            ms.Seek(0L, SeekOrigin.Begin) |> ignore
            let rtData = Serialiser.deserialise<Option<string>[]> model ms
            equal rtData typeToTest "Type not equal"
```
fails with NullReferenceException, but passes if that None in the middle is removed. If registerTypeIntoModel is used instead of registerRecordIntoModel it tries to register Option as union and it fails on None too.

And I don't understand why these 2 lines are there:
https://github.com/mvkara/protobuf-net-fsharp/blob/da72fed8939e0ae53b5985e1e4558ceb9886455c/test/ProtoBuf.FSharp.Unit/TestRecordRoundtrip.fs#L57-L58

**Comment by mvkara** [comment]
There is a Serialiser.registerOptionTypesIntoModel method which is what I was thinking of using. My cases only involved serialising option types as nested types and at times it paid to use this to customise their serialisation. However Protobuf doesn't like serializing null values at all from what I understand after doing a quick test so you are right - it isn't supported properly. https://github.com/protobuf-net/protobuf-net/blob/80dff1109bf49f6612baba9f7c2f03794477fa57/src/protobuf-net.Core/NetObjectCache.cs#L90. So while the wrapper allows you to register these types and builds the model; I only planned on supporting these "with effort" as nested types when originally writing this. I'm not sure it is possible (or worthwhile) to support this case. F#'s None case compiles down to 'null' rather than a union case which causes the issue. It could be possible to support ValueSome/ValueNull as an alternative.

On those lines they can be safely removed. Old lines from an old test (or a merge) most probably that I missed when refactoring this.

**Comment by mishun** [comment]
Shouldn't registerTypeIntoModel call registerOptionTypesIntoModel if passes option type then? And registerRecordIntoModel/registerUnionIntoModel assert that they were actually passed record/non-option union correspondingly?

**Comment by mvkara** [comment]
That function is exposed with extra args than the function you specified, and for nested types that method is called anyway with defaults. Given None at the root level can't be supported without working around Protobuf.net I don't see a reason to do that.

Anyway back on topic. I'm happy to take the PR if the project isn't significantly refactored (extra fs files only for the record surrogate generation) and the code is added for value records only. i.e. I would add an IF check if the record type is a value type. Let's do one change per PR at a time; otherwise I need more information before I can be confident to merge the PR (e.g. performance bench marking of old and new implementations)

**Comment by mishun** [comment]
"and the code is added for value records only. i.e. I would add an IF check if the record type is a value type"
... and if surrogate is needed at all. That's what code in the branch I referenced above does:
https://github.com/mishun/protobuf-net-fsharp/blob/5dae365f6b6857be09d47a970239c1ac3335236a/src/ProtoBuf.FSharp/ProtobufUtils.fs#L47

About minimal changes: surrogate generator has to somehow get list of "zero value assignments" so it has to significantly hack into existing code anyway. The only changes that weren't strictly neede were moving option surrogate into separate .fs file and emitting whole factory method with Reflection.Emit instead of separate setters (but at that point it was simpler that way and probably has better performance). I can definitely rebase it to current master plus try to add surrogates for value unions a bit later.

**Comment by mvkara** [comment]
Leave Value Unions as a separate PR. I will give your code a proper review soon as it is ready, and time permits me to do some benchmarking.

NOTE: As an example of a performance regression picked up that would be in a review skimming your code when the code changes too much Runtime.Serialization.FormatterServices.GetUninitializedObject and the use of that is extremely slow by a huge factor sadly hence why I try to use the parameterless constructor when possible. Hence I still recommend the use of CLIMutable in my comments.

To clarify I like your PR; just that when I originally wrote this performance should be comparable to the C# equivalent of manual Protobuf data classes (get; set;) properties; and to gracefully downgrade to lower performance modes to allow compatibility. Without adequate time to review I just want to make sure that this is right. Or rather I like F#; I don't want a significant performance penalty for using it. As an example I also wrote a collections library for F# (maps and sets) that had to have much better performance than C#'s immutable collections lib (and all of F# libs for that matter). From previous experience data structures and serialisation can take up a lot of overhead for a service so happy to benchmark this myself when your PR is ready (even if that means it takes a while to merge).

**Comment by mishun** [comment]
Runtime.Serialization.FormatterServices.GetUninitializedObject can be ditched for records in favor of calling regular record constructor with corresponding parameters (when it's accessible). Although, I don't know what protobuf-net does for types which have neither factory nor surrogate specified.

**Pull request closed without merging**
