### PR TITLE
Develop into master

### PR DESCRIPTION
**Pull request by mvkara**
- Value Type Surrogates
- Clean up of new generation code for further explanation and F# style changes.

### CODE REVIEW

**Comment by mvkara** [comment]
Added test cases from @mishun 's PR #14 that now break. This needs to be fixed before I can merge to master (if possible)

**Comment by mishun** [comment]
Dammit, I tend to forget when value types are passed by value and when --- by managed pointer. That explains segfault. Failing tests are a bit trickier: protobuf-net seems to ignore surrogate's default constructor despite
https://github.com/mvkara/protobuf-net-fsharp/blob/2d55897b24db39d9cef02ec9343141785d7aa3fe/src/ProtoBuf.FSharp/ProtobufUtils.fs#L55
(even when surrogate is reference type).
I moved that logic from constructor to op_Implicit and that seems to work: #16.

**Comment by mishun** [comment]
I also think that adding test cases may be a bit more convenient if they're picked up with reflection automatically (kinda like that: https://github.com/mishun/protobuf-net-fsharp/commit/9f301daf34586a2cab19a26eead017254099ee84)

**Comment by mvkara** [comment]
I do understand having auto reflection on the types. I only sparingly use reflection, and reflection.emit in my code. IMO its easy to get wrong and create invalid programs. For the tests I prefer F#'s explicit style vs using reflection for auto-discovery. Hence I wouldn't use that in my tests especially when it adds more code than before but that's just me.

As an example if we could convert the CodeGen.fs into F# quotation compiles (e.g. maybe using ProvidedTypes API) I would actually be happier with it, as I would feel there's less chance of human error bugs.

**Comment by mvkara** [comment]
Thanks @mishun for the change. New version (0.2.0) published to Nuget.

**Pull request merged**
