### PR TITLE
Quick fixes for zero array initialization and method quotation

### PR DESCRIPTION
**Pull request by mishun**

### CODE REVIEW

**Review by mvkara — COMMENTED** [review]
Is it possible to add the test cases that failed for this? Then I can pass the PR. Thanks!

**Comment by mishun** [comment]
For quotation it would be just using `int list`, for example, but that test won't pass, it would fail in different place since collections are not working yet. Zero array is a bit trickier: it's undefined behavior and potentially may explode somewhere but since the array has zero length it's element type is never actually inspected so it silently works (I accidentally stumbled upon that while looking how to fix `Some [||]` problem). Something that explicitly looks into types with reflection may catch that, I guess?

**Comment by mvkara** [comment]
If I understand the problem correctly I thought that the `Some null` case could be detected via a `isNull` check or an `Unchecked.defaultOf` equality.

i.e. `match roundtripOption with | Some x when isNull x -> failwith "Zero array not defaulted" | _ -> ()`

Since it is a test I'm not as fussed on how it is done, as long as it is explanatory to the reader of the code and clean.

To answer your other question at the current time F# collections aren't supported; as per the README.md it is recommended to use arrays in your contract types for the moment since they will be supported everywhere. So the FSharpList<_> type not working is expected as of right now.

**Comment by mishun** [comment]
The problem is zero value for array gets generated, but instead of `int[]`, for example, it has type `int[][]`. Comparator for test case sees that both array have zero length and assumes them equal without looking at types, so it doesn't catch that.

I can add fix for `Some [| |]` and corresponding test case here --- it should test for that problem too.

**Review by mvkara — APPROVED** [review]
LGTM.

**Pull request merged**
